### PR TITLE
Replace short format attribute name(s) on update.

### PR DESCRIPTION
**Pull request by eshryane**

### CODE REVIEW

**Comment by eshryane** [comment]
Need to review failing integration tests (maybe due to NWI-5 changes)
* AutNumIntegrationSpec
* DeleteMaintainerSpec
* OutOfRegionSpec
* PendingRouteSpec

**Comment by eshryane** [comment]
@job Also deployed to production with Whois 1.92.4 yesterday

**Comment by job** [comment]
This still seems broken:

```mntner:         mine
admin-c:        DH2607-RIPE
auth:           SSO # Filtered
mb:             Mine
*mb: Mine
mnt-by:         mine
created:        2010-11-02T13:17:09Z
last-modified:  2017-08-21T09:21:05Z
source:         RIPE # Filtered```

**Comment by eshryane** [comment]
@Job The code was fixed, but I've now also corrected the 3 objects containing short format attributes:

MNTNER mine
PERSON mh2198-ripe
PERSON DH3037-RIPE

**Pull request merged**
