### PR TITLE
Use mail.smtp.port to configure sending mail

### PR DESCRIPTION
**Pull request by eshryane**

### CODE REVIEW

**Review by dadepo — APPROVED** [review]

**Comment by eshryane** [comment]
Test failing in `net.ripe.db.whois.query.integration.SimpleTestIntegration`

**Comment by eshryane** [comment]
Deployed branch (commit 0263f7935c6f32491a4b033692dbd40a83a1fd45) to AWS and update delay dropped from 2 minutes to 20 seconds (maybe 2 emails were attempted to be sent?). This confirms that the JavaMail property values are being picked up.

**Comment by eshryane** [comment]
Tested mail delivery now working in AWS

**Comment by eshryane** [comment]
Confirmed integration tests are passing in merged PR to master commit e67a54522484e3812019fa2a07eecd673cc6549c

**Pull request merged**
