### PR TITLE
Use new default mntner table

### PR DESCRIPTION
**Pull request by maggarwal13**

### CODE REVIEW

**Comment by MiguelAHM** [comment]
Should we include this change in the current release or should we create a bug fix and create a new release?

**Comment by maggarwal13** [comment]
> Should we include this change in the current release or should we create a bug fix and create a new release?

**Comment by maggarwal13** [comment]
> > Should we include this change in the current release or should we create a bug fix and create a new release?

I am not sure, we need to discuss with Ed but in any case this need to be merged to master

**Comment by MiguelAHM** [comment]
is it ok to call to the internal database from whois, instead of using whois-internal? (I though that we were accessing internal schema's databases just from whois-internal

**Comment by maggarwal13** [comment]
> is it ok to call to the internal database from whois, instead of using whois-internal? (I though that we were accessing internal schema's databases just from whois-internal

Not true we do lot of places in whois codebase. Search for usage if internalsTemplate. I would not put a dependency of whois-internal service being available for whois to run properly.

**Review by MiguelAHM — APPROVED** [review]

**Pull request merged**
